<?php

namespace Drupal\Core\Tests;

use Drupal\Core\BootstrapPhases;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-31 at 11:02:00.
 */
class BootstrapPhasesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BootstrapPhases
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BootstrapPhases();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Drupal\Core\BootstrapPhases::offsetExists
     * @todo   Implement testOffsetExists().
     */
    public function testOffsetExists()
    {
        $this->assertArrayHasKey(BootstrapPhases::FULL, $this->object);
    }

    /**
     * @covers Drupal\Core\BootstrapPhases::offsetGet
     */
    public function testOffsetGet()
    {
        $this->assertInternalType('callable', $this->object[BootstrapPhases::FULL]);
    }

    /**
     * @covers Drupal\Core\BootstrapPhases::offsetSet
     */
    public function testOffsetSet()
    {
        $this->setExpectedException('InvalidArgumentException');
        $this->object[5] = function () { };
    }

    /**
     * @covers Drupal\Core\BootstrapPhases::offsetUnset
     */
    public function testOffsetUnset()
    {
        $this->setExpectedException('InvalidArgumentException');
        unset($this->object[3]);
    }

    /**
     * @covers Drupal\Core\BootstrapPhases::keys
     */
    public function testKeys()
    {   $this->assertInternalType('array', $this->object->getPhases());
    }
}
